plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.xenia.emulator'
    compileSdk 33
    ndkVersion '26.1.10909125'

    defaultConfig {
        applicationId 'jp.xenia.emulator'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName 'Prototype'

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static',
                        '-DXENIA_BUILD_TESTS=OFF',
                        '-DXENIA_BUILD_MISC=OFF'
                targets 'xenia-app'
            }
        }

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        release {
            externalNativeBuild {
                cmake {
                    arguments '-DCMAKE_BUILD_TYPE=Release'
                }
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
            debuggable true
            externalNativeBuild {
                cmake {
                    arguments '-DCMAKE_BUILD_TYPE=Debug'
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('../../../CMakeLists.txt')
            version '3.22.1'
        }
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:15.0'
}
