#!/usr/bin/env python3
"""Merge xenia-manager/optimized-settings TOMLs into recommended_settings.toml."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    tomllib = None  # type: ignore


def load_toml(path: Path) -> dict:
    if tomllib is None:
        raise SystemExit("Python 3.11+ required (tomllib).")
    return tomllib.loads(path.read_text(encoding="utf-8"))


def flatten_sections(data: dict) -> dict[str, object]:
    flat: dict[str, object] = {}
    for key, value in data.items():
        if key in ("title_name",):
            flat[key] = value
            continue
        if isinstance(value, dict):
            for sub_key, sub_val in value.items():
                flat[str(sub_key)] = sub_val
        else:
            flat[str(key)] = value
    return flat


def title_id_from_filename(name: str) -> str | None:
    match = re.match(r"^([0-9A-Fa-f]{8})\.toml$", name)
    if not match:
        return None
    return match.group(1).upper()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--source-dir",
        type=Path,
        required=True,
        help="Path to xenia-manager optimized-settings/settings/",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path("config/recommended_settings.toml"),
        help="Output recommended_settings.toml path",
    )
    ap.add_argument(
        "--header",
        type=Path,
        default=None,
        help="Optional base TOML merged first (e.g. hand-curated smoke titles)",
    )
    args = ap.parse_args()

    if not args.source_dir.is_dir():
        print(f"Missing source dir: {args.source_dir}", file=sys.stderr)
        return 1

    merged: dict[str, dict[str, object]] = {}

    if args.header and args.header.is_file():
        header = load_toml(args.header)
        for title_id, section in header.items():
            if isinstance(section, dict):
                merged[str(title_id).upper()] = flatten_sections(section)

    for path in sorted(args.source_dir.glob("*.toml")):
        tid = title_id_from_filename(path.name)
        if not tid:
            continue
        data = load_toml(path)
        section: dict[str, object] = merged.setdefault(tid, {})
        flat = flatten_sections(data)
        title_name = flat.pop("title_name", None)
        if title_name and "title_name" not in section:
            section["title_name"] = title_name
        section.update(flat)

    lines = [
        "# Recommended per-game settings for Phoenix.",
        "# Generated by tools/tier0/import_recommended_settings.py",
        "# Community-maintained. Shipped read-only with the emulator.",
        "",
    ]
    for tid in sorted(merged.keys()):
        section = merged[tid]
        lines.append(f"[{tid}]")
        if "title_name" in section:
            lines.append(f'title_name = "{section["title_name"]}"')
        for key in sorted(k for k in section.keys() if k != "title_name"):
            val = section[key]
            if isinstance(val, bool):
                lines.append(f"{key} = {'true' if val else 'false'}")
            elif isinstance(val, (int, float)):
                lines.append(f"{key} = {val}")
            else:
                lines.append(f'{key} = "{val}"')
        lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.out} ({len(merged)} titles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
